### PR TITLE
add Caddy installation and instructions

### PR DESCRIPTION
**Pull request by polyrand**
The Caddyfile needs a bit of testing to make sure everything works as expected.

I'm creating the pull requests as a way to discuss if this could be a part of fastsetup. In that case, I can provide more comments in the Caddyfile to make it easy to edit and adapt, as well as doing more thorough testing.

### CODE REVIEW

**Comment by jph00** [comment]
Yes I do want to provide caddy setup, although I want it to be entirely generated by scripts, not something that requires editing a config file by hand.

**Comment by polyrand** [comment]
Ok I understand, so you mean something like:

```bash
[[ -z $DOMAIN ]] && read -e -p "Enter domain to set: " DOMAIN
[[ -z $BACKENDPORT ]] && read -e -p "Enter the port where your app is running: " BACKENDPORT

# ...
# ...
# ...

cat << 'EOF' >> ~/Caddyfile
$DOMAIN {
  encode zstd gzip

  # load balance between replicas
  reverse_proxy localhost:$BACKENDPORT {
	lb_policy least_conn
  }


  log {
    output file /var/log/caddy.$DOMAIN.log {
        roll_size 20MiB
	roll_keep 2
	roll_keep_for 720h
    }
  }
}

www.$DOMAIN {
  redir https://$DOMAIN{uri} permanent
}
EOF
```

But in that case there should be a few if statements in case you need:
* Load balancing between many upstreams
* Add http auth (or not, and just leave that to the upstream app)
* Listen on a port rather than a domain
* Etc.

What's your idea regarding that?

**Comment by jph00** [comment]
> But in that case there should be a few if statements in case you need:

>  * Load balancing between many upstreams
>  * Add http auth (or not, and just leave that to the upstream app)
>  * Listen on a port rather than a domain
>  * Etc.
> What's your idea regarding that?


Just support the initial minimal basics, and folks that need complex stuff can add it themselves, including by using the Caddy API.

FYI you can grab the current public IP in a script with:
dig +short myip.opendns.com @resolver1.opendns.com

**Comment by polyrand** [comment]
Perfect, I can start working on something like that.

Regarding the IP, I think it can't be automated that way. My idea was having restricted access to the reverse proxy only to the "home" IP of the owner. So the person would have to run that command from their own computer, not the server.

An option can be using either:

```bash
echo $SSH_CLIENT | awk '{print $1}'
``` 
or
```bash
echo $SSH_CONNECTION | awk '{print $1}
```

To get the IP address of the client in the SSH session (there should only be one).

**Comment by polyrand** [comment]
Anyway, I think it may be easier for the user to just add HTTP auth to the Caddyfile if they want to restrict access to the web server? Messing with blocking IPs may cause trouble if an ISP changes your address, because then you have to edit the Caddyfile and change the IPs.

**Comment by jph00** [comment]
> Regarding the IP, I think it can't be automated that way. My idea was having restricted access to the reverse proxy only to the "home" IP of the owner. So the person would have to run that command from their own computer, not the server.

No, the idea of the scripts in this repo is that they're run on the server.

**Comment by jph00** [comment]
> Anyway, I think it may be easier for the user to just add HTTP auth to the Caddyfile if they want to restrict access to the web server? Messing with blocking IPs may cause trouble if an ISP changes your address, because then you have to edit the Caddyfile and change the IPs.

Right, you shouldn't set up any IP restrictions or other auth.

**Comment by polyrand** [comment]
I've made the necessary changes. I'll try running everything on a fresh server later to check it works.

**Comment by jph00** [comment]
Thanks for all this! It'll be a while (possibly months) before I can spend time looking at Caddy, so I'll leave this open until that time.

**Comment by polyrand** [comment]
Sure, no problem! If someone is interested in Caddy in the context of fastsetup, they will probably find this. Even if you decide to use something else like Nginx, that's perfectly fine!

In the meantime, in case someone is interested, I'll have a [personal fork of fastsetup in a different branch](https://github.com/polyrand/fastsetup/tree/personal) with a Caddy template, docker setup and other complementary stuff.

**Comment by jph00** [comment]
I've finally gotten around to looking at caddy. This PR is very cool, but it's more complex then I'm looking for - so instead I'm going to add a super-simple installer to this project.

**Comment by polyrand** [comment]
Perfect, no problem! From what I've seen in the installation scripts, I think the systemd service file is missing.

**Comment by jph00** [comment]
> Perfect, no problem! From what I've seen in the installation scripts, I think the systemd service file is missing.


Well spotted!

**Pull request closed without merging**
